### ISSUE TITLE
Minor Documentation Issue

### ISSUE THREAD

**Issue by NicholasLYang** [albinotonnina/react-magic-hat#2]
Just a small question, in this example, 

```
import YourMagicContainer from 'react-magic-hat'
import ComponentA, {id as CompA} from 'components'
import ComponentB from 'components'

const renderFrame = ({id, actions}) => {
  const Component = id === CompA ? ComponentA : ComponentB

  return <Component {...props} {...actions} />
}

const Layout = () => (
  <div>
    <YourMagicContainer renderFrame={renderFrame} />
  </div>
)
```

Where is the `props` coming from in the `renderFrame` function? Should there be another argument destructured from `pageObject`? Thanks!

**Comment by albinotonnina** [comment]
Hello @NicholasLYang 
Thank you very much for opening the issue. 
I fixed and also tried to clarify a bit more how that part works.

I'm gonna close the issue but feel free to reopen if you think it should be reopened.
Thanks again!
